//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemonOrange.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.UploadSoap")]
    public interface UploadSoap {
        
        // CODEGEN: Generating message contract since element name Txt from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJsom", ReplyAction="*")]
        DemonOrange.ServiceReference.GetJsomResponse GetJsom(DemonOrange.ServiceReference.GetJsomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJsom", ReplyAction="*")]
        System.Threading.Tasks.Task<DemonOrange.ServiceReference.GetJsomResponse> GetJsomAsync(DemonOrange.ServiceReference.GetJsomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarServico", ReplyAction="*")]
        bool VerificarServico();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarServico", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> VerificarServicoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DandoCarga", ReplyAction="*")]
        bool DandoCarga();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DandoCarga", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DandoCargaAsync();
        
        // CODEGEN: Generating message contract since element name UltimaAttResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UltimaAtt", ReplyAction="*")]
        DemonOrange.ServiceReference.UltimaAttResponse UltimaAtt(DemonOrange.ServiceReference.UltimaAttRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UltimaAtt", ReplyAction="*")]
        System.Threading.Tasks.Task<DemonOrange.ServiceReference.UltimaAttResponse> UltimaAttAsync(DemonOrange.ServiceReference.UltimaAttRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJsomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJsom", Namespace="http://tempuri.org/", Order=0)]
        public DemonOrange.ServiceReference.GetJsomRequestBody Body;
        
        public GetJsomRequest() {
        }
        
        public GetJsomRequest(DemonOrange.ServiceReference.GetJsomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetJsomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DemonOrange.ServiceReference.ArrayOfString Txt;
        
        public GetJsomRequestBody() {
        }
        
        public GetJsomRequestBody(DemonOrange.ServiceReference.ArrayOfString Txt) {
            this.Txt = Txt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJsomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJsomResponse", Namespace="http://tempuri.org/", Order=0)]
        public DemonOrange.ServiceReference.GetJsomResponseBody Body;
        
        public GetJsomResponse() {
        }
        
        public GetJsomResponse(DemonOrange.ServiceReference.GetJsomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetJsomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetJsomResult;
        
        public GetJsomResponseBody() {
        }
        
        public GetJsomResponseBody(string GetJsomResult) {
            this.GetJsomResult = GetJsomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UltimaAttRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UltimaAtt", Namespace="http://tempuri.org/", Order=0)]
        public DemonOrange.ServiceReference.UltimaAttRequestBody Body;
        
        public UltimaAttRequest() {
        }
        
        public UltimaAttRequest(DemonOrange.ServiceReference.UltimaAttRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UltimaAttRequestBody {
        
        public UltimaAttRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UltimaAttResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UltimaAttResponse", Namespace="http://tempuri.org/", Order=0)]
        public DemonOrange.ServiceReference.UltimaAttResponseBody Body;
        
        public UltimaAttResponse() {
        }
        
        public UltimaAttResponse(DemonOrange.ServiceReference.UltimaAttResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UltimaAttResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UltimaAttResult;
        
        public UltimaAttResponseBody() {
        }
        
        public UltimaAttResponseBody(string UltimaAttResult) {
            this.UltimaAttResult = UltimaAttResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UploadSoapChannel : DemonOrange.ServiceReference.UploadSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadSoapClient : System.ServiceModel.ClientBase<DemonOrange.ServiceReference.UploadSoap>, DemonOrange.ServiceReference.UploadSoap {
        
        public UploadSoapClient() {
        }
        
        public UploadSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemonOrange.ServiceReference.GetJsomResponse DemonOrange.ServiceReference.UploadSoap.GetJsom(DemonOrange.ServiceReference.GetJsomRequest request) {
            return base.Channel.GetJsom(request);
        }
        
        public string GetJsom(DemonOrange.ServiceReference.ArrayOfString Txt) {
            DemonOrange.ServiceReference.GetJsomRequest inValue = new DemonOrange.ServiceReference.GetJsomRequest();
            inValue.Body = new DemonOrange.ServiceReference.GetJsomRequestBody();
            inValue.Body.Txt = Txt;
            DemonOrange.ServiceReference.GetJsomResponse retVal = ((DemonOrange.ServiceReference.UploadSoap)(this)).GetJsom(inValue);
            return retVal.Body.GetJsomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemonOrange.ServiceReference.GetJsomResponse> DemonOrange.ServiceReference.UploadSoap.GetJsomAsync(DemonOrange.ServiceReference.GetJsomRequest request) {
            return base.Channel.GetJsomAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemonOrange.ServiceReference.GetJsomResponse> GetJsomAsync(DemonOrange.ServiceReference.ArrayOfString Txt) {
            DemonOrange.ServiceReference.GetJsomRequest inValue = new DemonOrange.ServiceReference.GetJsomRequest();
            inValue.Body = new DemonOrange.ServiceReference.GetJsomRequestBody();
            inValue.Body.Txt = Txt;
            return ((DemonOrange.ServiceReference.UploadSoap)(this)).GetJsomAsync(inValue);
        }
        
        public bool VerificarServico() {
            return base.Channel.VerificarServico();
        }
        
        public System.Threading.Tasks.Task<bool> VerificarServicoAsync() {
            return base.Channel.VerificarServicoAsync();
        }
        
        public bool DandoCarga() {
            return base.Channel.DandoCarga();
        }
        
        public System.Threading.Tasks.Task<bool> DandoCargaAsync() {
            return base.Channel.DandoCargaAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemonOrange.ServiceReference.UltimaAttResponse DemonOrange.ServiceReference.UploadSoap.UltimaAtt(DemonOrange.ServiceReference.UltimaAttRequest request) {
            return base.Channel.UltimaAtt(request);
        }
        
        public string UltimaAtt() {
            DemonOrange.ServiceReference.UltimaAttRequest inValue = new DemonOrange.ServiceReference.UltimaAttRequest();
            inValue.Body = new DemonOrange.ServiceReference.UltimaAttRequestBody();
            DemonOrange.ServiceReference.UltimaAttResponse retVal = ((DemonOrange.ServiceReference.UploadSoap)(this)).UltimaAtt(inValue);
            return retVal.Body.UltimaAttResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemonOrange.ServiceReference.UltimaAttResponse> DemonOrange.ServiceReference.UploadSoap.UltimaAttAsync(DemonOrange.ServiceReference.UltimaAttRequest request) {
            return base.Channel.UltimaAttAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemonOrange.ServiceReference.UltimaAttResponse> UltimaAttAsync() {
            DemonOrange.ServiceReference.UltimaAttRequest inValue = new DemonOrange.ServiceReference.UltimaAttRequest();
            inValue.Body = new DemonOrange.ServiceReference.UltimaAttRequestBody();
            return ((DemonOrange.ServiceReference.UploadSoap)(this)).UltimaAttAsync(inValue);
        }
    }
}
