//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteServio.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WSArquivoSoap")]
    public interface WSArquivoSoap {
        
        // CODEGEN: Generating message contract since element name docbinaryarray from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDocument", ReplyAction="*")]
        TesteServio.ServiceReference1.SaveDocumentResponse SaveDocument(TesteServio.ServiceReference1.SaveDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<TesteServio.ServiceReference1.SaveDocumentResponse> SaveDocumentAsync(TesteServio.ServiceReference1.SaveDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDocument", Namespace="http://tempuri.org/", Order=0)]
        public TesteServio.ServiceReference1.SaveDocumentRequestBody Body;
        
        public SaveDocumentRequest() {
        }
        
        public SaveDocumentRequest(TesteServio.ServiceReference1.SaveDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] docbinaryarray;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        public SaveDocumentRequestBody() {
        }
        
        public SaveDocumentRequestBody(byte[] docbinaryarray, string key) {
            this.docbinaryarray = docbinaryarray;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public TesteServio.ServiceReference1.SaveDocumentResponseBody Body;
        
        public SaveDocumentResponse() {
        }
        
        public SaveDocumentResponse(TesteServio.ServiceReference1.SaveDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveDocumentResult;
        
        public SaveDocumentResponseBody() {
        }
        
        public SaveDocumentResponseBody(bool SaveDocumentResult) {
            this.SaveDocumentResult = SaveDocumentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSArquivoSoapChannel : TesteServio.ServiceReference1.WSArquivoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSArquivoSoapClient : System.ServiceModel.ClientBase<TesteServio.ServiceReference1.WSArquivoSoap>, TesteServio.ServiceReference1.WSArquivoSoap {
        
        public WSArquivoSoapClient() {
        }
        
        public WSArquivoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSArquivoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSArquivoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSArquivoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TesteServio.ServiceReference1.SaveDocumentResponse TesteServio.ServiceReference1.WSArquivoSoap.SaveDocument(TesteServio.ServiceReference1.SaveDocumentRequest request) {
            return base.Channel.SaveDocument(request);
        }
        
        public bool SaveDocument(byte[] docbinaryarray, string key) {
            TesteServio.ServiceReference1.SaveDocumentRequest inValue = new TesteServio.ServiceReference1.SaveDocumentRequest();
            inValue.Body = new TesteServio.ServiceReference1.SaveDocumentRequestBody();
            inValue.Body.docbinaryarray = docbinaryarray;
            inValue.Body.key = key;
            TesteServio.ServiceReference1.SaveDocumentResponse retVal = ((TesteServio.ServiceReference1.WSArquivoSoap)(this)).SaveDocument(inValue);
            return retVal.Body.SaveDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TesteServio.ServiceReference1.SaveDocumentResponse> TesteServio.ServiceReference1.WSArquivoSoap.SaveDocumentAsync(TesteServio.ServiceReference1.SaveDocumentRequest request) {
            return base.Channel.SaveDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TesteServio.ServiceReference1.SaveDocumentResponse> SaveDocumentAsync(byte[] docbinaryarray, string key) {
            TesteServio.ServiceReference1.SaveDocumentRequest inValue = new TesteServio.ServiceReference1.SaveDocumentRequest();
            inValue.Body = new TesteServio.ServiceReference1.SaveDocumentRequestBody();
            inValue.Body.docbinaryarray = docbinaryarray;
            inValue.Body.key = key;
            return ((TesteServio.ServiceReference1.WSArquivoSoap)(this)).SaveDocumentAsync(inValue);
        }
    }
}
