//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemonOrange.WSArquivo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSArquivo.WSArquivoSoap")]
    public interface WSArquivoSoap {
        
        // CODEGEN: Generating message contract since element name docbinaryarray from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDocument", ReplyAction="*")]
        DemonOrange.WSArquivo.SaveDocumentResponse SaveDocument(DemonOrange.WSArquivo.SaveDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDocument", Namespace="http://tempuri.org/", Order=0)]
        public DemonOrange.WSArquivo.SaveDocumentRequestBody Body;
        
        public SaveDocumentRequest() {
        }
        
        public SaveDocumentRequest(DemonOrange.WSArquivo.SaveDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] docbinaryarray;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int tipo;
        
        public SaveDocumentRequestBody() {
        }
        
        public SaveDocumentRequestBody(byte[] docbinaryarray, string key, int tipo) {
            this.docbinaryarray = docbinaryarray;
            this.key = key;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public DemonOrange.WSArquivo.SaveDocumentResponseBody Body;
        
        public SaveDocumentResponse() {
        }
        
        public SaveDocumentResponse(DemonOrange.WSArquivo.SaveDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveDocumentResult;
        
        public SaveDocumentResponseBody() {
        }
        
        public SaveDocumentResponseBody(bool SaveDocumentResult) {
            this.SaveDocumentResult = SaveDocumentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSArquivoSoapChannel : DemonOrange.WSArquivo.WSArquivoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSArquivoSoapClient : System.ServiceModel.ClientBase<DemonOrange.WSArquivo.WSArquivoSoap>, DemonOrange.WSArquivo.WSArquivoSoap {
        
        public WSArquivoSoapClient() {
        }
        
        public WSArquivoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSArquivoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSArquivoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSArquivoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemonOrange.WSArquivo.SaveDocumentResponse DemonOrange.WSArquivo.WSArquivoSoap.SaveDocument(DemonOrange.WSArquivo.SaveDocumentRequest request) {
            return base.Channel.SaveDocument(request);
        }
        
        public bool SaveDocument(byte[] docbinaryarray, string key, int tipo) {
            DemonOrange.WSArquivo.SaveDocumentRequest inValue = new DemonOrange.WSArquivo.SaveDocumentRequest();
            inValue.Body = new DemonOrange.WSArquivo.SaveDocumentRequestBody();
            inValue.Body.docbinaryarray = docbinaryarray;
            inValue.Body.key = key;
            inValue.Body.tipo = tipo;
            DemonOrange.WSArquivo.SaveDocumentResponse retVal = ((DemonOrange.WSArquivo.WSArquivoSoap)(this)).SaveDocument(inValue);
            return retVal.Body.SaveDocumentResult;
        }
    }
}
