//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batalhas
    {
        public Batalhas()
        {
            this.Lutas = new HashSet<Lutas>();
            this.PlayerOponente = new HashSet<PlayerOponente>();
            this.PlayerStatus = new HashSet<PlayerStatus>();
        }
    
        public long ID { get; set; }
        public string Guilda { get; set; }
        public Nullable<long> Life { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<long> PontuacaoOponente { get; set; }
        public Nullable<long> PontuacaoGuild { get; set; }
        public Nullable<long> RankGuild { get; set; }
        public Nullable<long> idGuilda { get; set; }
    
        public virtual ICollection<Lutas> Lutas { get; set; }
        public virtual ICollection<PlayerOponente> PlayerOponente { get; set; }
        public virtual ICollection<PlayerStatus> PlayerStatus { get; set; }
    }
}
