//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lutas
    {
        public long ID { get; set; }
        public Nullable<long> CodBatalhas { get; set; }
        public Nullable<long> CodPlayer { get; set; }
        public Nullable<long> CodPlayerOponente { get; set; }
        public Nullable<int> Vitoria { get; set; }
        public Nullable<long> ValorBarra { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public string MomentoVitoria { get; set; }
    
        public virtual Batalhas Batalhas { get; set; }
        public virtual Player Player { get; set; }
        public virtual PlayerOponente PlayerOponente { get; set; }
    }
}
