//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SW_GuildEntities : DbContext
    {
        public DB_SW_GuildEntities()
            : base(BLO.Conexao.ObterStringConexao())
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Batalhas> Batalhas { get; set; }
        public DbSet<Lutas> Lutas { get; set; }
        public DbSet<Player> Player { get; set; }
        public DbSet<PlayerOponente> PlayerOponente { get; set; }
        public DbSet<PlayerStatus> PlayerStatus { get; set; }
        public DbSet<PlayerDefesas> PlayerDefesas { get; set; }
    }
}
