//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Lutas = new HashSet<Lutas>();
            this.PlayerStatus = new HashSet<PlayerStatus>();
            this.PlayerDefesas = new HashSet<PlayerDefesas>();
        }
    
        public long ID { get; set; }
        public string Nome { get; set; }
        public Nullable<long> Level { get; set; }
        public Nullable<long> PontoArena { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Lutas> Lutas { get; set; }
        public virtual ICollection<PlayerStatus> PlayerStatus { get; set; }
        public virtual ICollection<PlayerDefesas> PlayerDefesas { get; set; }
    }
}
