//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerOponente
    {
        public PlayerOponente()
        {
            this.Lutas = new HashSet<Lutas>();
        }
    
        public long ID { get; set; }
        public Nullable<long> CodGuilda { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Bonus { get; set; }
    
        public virtual Batalhas Batalhas { get; set; }
        public virtual ICollection<Lutas> Lutas { get; set; }
    }
}
