//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerDefesas
    {
        public long ID { get; set; }
        public Nullable<long> IdPlayer { get; set; }
        public string NomeOponente { get; set; }
        public string NomeGuilda { get; set; }
        public Nullable<int> Vitoria { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
